module.exports = {
  env: {
    MONGODB_USERNAME: process.env.MONGODB_USERNAME,
    MONGODB_PASSWORD: process.env.MONGODB_PASSWORD,
    MONGODB_CLUSTER_NAME: process.env.MONGODB_CLUSTER_NAME,
    MONGODB_DATABASE_NAME: process.env.MONGODB_DATABASE_NAME,
    MAILJET_API_KEY: process.env.MAILJET_API_KEY,
    MAILJET_SECRET_KEY: process.env.MAILJET_SECRET_KEY,
    APPLICATION_MAIL: process.env.APPLICATION_MAIL,
    NEXT_PUBLIC_SITE_URL: process.env.NEXT_PUBLIC_SITE_URL,
  },
}
